import React, { useState } from "react";
import { 
  FileText, 
  Download, 
  Share2, 
  Bot, 
  ShieldAlert, 
  Cpu, 
  HelpCircle, 
  CheckCircle, 
  ArrowRight,
  TrendingUp,
  FileDown
} from "lucide-react";
import { exportToPdf } from "../lib/pdfExport";
import ShareDialog from "./ShareDialog";
import NotificationToast from "./NotificationToast";

interface IncidentReportData {
  id: string;
  targetUser: string;
  riskScore: number;
  threatLevel: string;
  summary: string;
  rootCause: string;
  evidence: string[];
  explanation: string;
  mitigationPlan: string[];
}

export default function IncidentReportsView() {
  const [selectedIncidentId, setSelectedIncidentId] = useState("INC-9921");

  const reports: Record<string, IncidentReportData> = {
    "INC-9921": {
      id: "INC-9921",
      targetUser: "Rahul S. (Senior DBA)",
      riskScore: 96,
      threatLevel: "Critical - Active Data Exfiltration",
      summary: "Privileged Database Administrator Rahul S. was flagged initiating an unscheduled backup schema dump of the Oracle Customer Vault. Session egress volume was mapped exceeding the 30-day baseline by 1,200% over a 15-minute window, routing to an unvetted Moscow VPN proxy subnet.",
      rootCause: "Compromised SSO credential or malicious insider activity during off-hours, utilizing a residential proxy tunnel to bypass geographic location step-up checks.",
      evidence: [
        "SQL Query Entropy Hash: 0xf391aef02bc",
        "Egress volume mapped at 4.8 GB (Limit: 50MB)",
        "Authorized MAC address hardware profile mismatch",
        "MFA challenge failed on third continuous attempt"
      ],
      explanation: "AegisSOC neural model mapped the query sequence 'SELECT * FROM public.customer_portfolio_backup' as having 99.8% semantic correlation with malicious database exfiltration patterns rather than normal DBA rotational integrity tasks.",
      mitigationPlan: [
        "Isolate credentials of actor Rahul S. across all active AD domains",
        "Quarantine workstation MAC-ENG-892 via CrowdStrike SOAR command",
        "Force FIDO2 WebAuthn hardware token re-enrollment",
        "Roll forward Oracle vault database backup encryption keys"
      ]
    },
    "INC-8831": {
      id: "INC-8831",
      targetUser: "Meera K. (Wealth Manager)",
      riskScore: 78,
      threatLevel: "High - Bulk Portfolio Export",
      summary: "Wealth Management console flagged exporting 120 premium client portfolios during non-business hours (11:10 PM EST). Device trust validation failed on the VPN endpoint signature.",
      rootCause: "Session hijacking or rogue operator harvesting lead sheets prior to contract termination window.",
      evidence: [
        "Export velocity: 12 portfolios / sec",
        "Workstation IP mapped to public airport Wi-Fi subnet",
        "Anomalous ZIP file packaging trigger"
      ],
      explanation: "AegisSOC categorized this as a highly anomalous action sequence contradicting the actor's 90-day operational profile (mean daily exports: 2 portfolios).",
      mitigationPlan: [
        "Apply POL-03: Restrict active session download privileges",
        "Revoke Wealth Console access until manual clearance",
        "Enforce emergency outbound packet audit on local network node"
      ]
    }
  };

  const activeReport = reports[selectedIncidentId] || reports["INC-9921"];

  const [isShareOpen, setIsShareOpen] = useState(false);
  const [toast, setToast] = useState<{ message: string; type: "success" | "info" | "error" } | null>(null);

  const handleDownload = () => {
    try {
      exportToPdf({
        title: `AegisSOC Cyber Incident Report: ${activeReport.id}`,
        metadata: {
          "Report Reference": activeReport.id,
          "Target User Focus": activeReport.targetUser,
          "Incident Risk Index": `${activeReport.riskScore} / 100`,
          "Threat Category": activeReport.threatLevel,
          "System Handshake": "NIST CSF Standard",
          "Generated By": "spugazhenthi1005@gmail.com"
        },
        sections: [
          {
            title: "Executive Incident Summary",
            content: activeReport.summary
          },
          {
            title: "Assigned Forensics Root Cause",
            content: activeReport.rootCause
          },
          {
            title: "Core Cognitive Explanation",
            content: activeReport.explanation
          },
          {
            title: "Discovered Evidence Chain",
            content: activeReport.evidence
          },
          {
            title: "Mandated Playbook Mitigation actions",
            content: activeReport.mitigationPlan
          }
        ]
      }, `${activeReport.id}_AegisSOC_Forensic_Report.pdf`);

      setToast({
        message: `Forensic report ${activeReport.id} compiled and downloaded successfully as certified PDF!`,
        type: "success"
      });
    } catch (e: any) {
      setToast({
        message: `Error compiling PDF: ${e?.message || e}`,
        type: "error"
      });
    }
  };

  const handleShare = () => {
    setIsShareOpen(true);
  };

  return (
    <>
      <div className="space-y-6">
      {/* Header Panel */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 bg-[#111827]/30 p-5 rounded-2xl border border-outline-variant/20">
        <div>
          <h2 className="text-xl font-bold text-on-surface flex items-center gap-2">
            <FileText className="h-5 w-5 text-primary-container" />
            AI Cognitive Investigation Incident Reports
          </h2>
          <p className="text-xs text-on-surface-variant font-mono uppercase mt-0.5">
            SOAR compiled incidents with deep learning natural language logs and playbooks
          </p>
        </div>

        <div className="flex gap-2 text-xs">
          <button 
            onClick={handleDownload}
            className="px-3.5 py-2 border border-outline-variant/30 hover:border-primary-container text-on-surface-variant hover:text-on-surface font-mono rounded-lg transition-all flex items-center gap-1.5 cursor-pointer"
          >
            <FileDown className="h-4 w-4" />
            Download PDF
          </button>
          
          <button 
            onClick={handleShare}
            className="bg-primary-container text-on-primary-fixed hover:bg-primary-fixed px-4 py-2 rounded-lg font-mono text-xs font-bold transition-all flex items-center gap-1.5 cursor-pointer shadow-lg shadow-primary-container/10"
          >
            <Share2 className="h-3.5 w-3.5" />
            Share Report
          </button>
        </div>
      </div>

      {/* Selector and Main view */}
      <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">
        
        {/* Selector Sidebar */}
        <div className="soc-card p-5 space-y-4">
          <h3 className="text-xs font-bold font-mono text-on-surface uppercase tracking-wide">
            Generated Case Archives
          </h3>

          <div className="space-y-2">
            {Object.keys(reports).map((id) => (
              <button
                key={id}
                onClick={() => setSelectedIncidentId(id)}
                className={`w-full text-left p-3.5 rounded-xl border transition-all cursor-pointer ${
                  selectedIncidentId === id 
                    ? "bg-primary-container/10 border-primary-container text-primary-container font-bold" 
                    : "bg-[#080f11] border-outline-variant/15 text-on-surface-variant hover:text-on-surface"
                }`}
              >
                <div className="flex justify-between items-center text-[10px] font-mono">
                  <span>{id}</span>
                  <span className={reports[id].riskScore >= 80 ? "text-error" : "text-tertiary-container"}>
                    Risk: {reports[id].riskScore}
                  </span>
                </div>
                <h4 className="text-xs font-bold text-on-surface mt-1 truncate">{reports[id].targetUser}</h4>
                <p className="text-[10px] text-on-surface-variant mt-0.5 truncate">{reports[id].threatLevel}</p>
              </button>
            ))}
          </div>
        </div>

        {/* Report Canvas */}
        <div className="lg:col-span-3 soc-card p-6 space-y-6">
          
          {/* Executive Header */}
          <div className="border-b border-outline-variant/20 pb-5 flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
            <div>
              <span className="text-[10px] font-mono text-error uppercase tracking-widest font-black">
                {activeReport.threatLevel}
              </span>
              <h3 className="text-xl font-bold text-on-surface mt-1">AegisSOC Cognitive Security Report — {activeReport.id}</h3>
              <p className="text-xs text-on-surface-variant mt-1">Subject Scope: {activeReport.targetUser} • Cryptographically verified compliance audit</p>
            </div>
            
            <div className="bg-[#080f11] p-3 rounded-xl border border-outline-variant/30 text-center">
              <span className="text-[10px] font-mono text-on-surface-variant uppercase block">Bayesian Hazard Score</span>
              <span className="text-2xl font-black text-error">{activeReport.riskScore} <span className="text-xs text-on-surface-variant font-normal">/ 100</span></span>
            </div>
          </div>

          {/* Chronological Summary & Root cause */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="space-y-2">
              <h4 className="text-xs font-bold font-mono text-on-surface uppercase tracking-wide">
                Executive Incident Summary
              </h4>
              <p className="text-xs text-on-surface-variant leading-relaxed bg-[#080f11] p-4 rounded-xl border border-outline-variant/15">
                {activeReport.summary}
              </p>
            </div>

            <div className="space-y-2">
              <h4 className="text-xs font-bold font-mono text-on-surface uppercase tracking-wide">
                Identified Root Cause
              </h4>
              <p className="text-xs text-on-surface-variant leading-relaxed bg-[#080f11] p-4 rounded-xl border border-outline-variant/15">
                {activeReport.rootCause}
              </p>
            </div>
          </div>

          {/* AI Decision reasoning & Explanation */}
          <div className="bg-primary-container/5 border border-primary-container/20 p-5 rounded-2xl space-y-3">
            <h4 className="text-xs font-bold font-mono text-primary-container uppercase tracking-wide flex items-center gap-1.5">
              <Bot className="h-4 w-4" />
              AegisSOC Cognitive Inference Reasoning
            </h4>
            <p className="text-xs text-on-surface-variant leading-relaxed">
              {activeReport.explanation}
            </p>
          </div>

          {/* Evidence Envelopes */}
          <div className="space-y-3">
            <h4 className="text-xs font-bold font-mono text-on-surface uppercase tracking-wide">
              Logged System Evidence Envelopes (Immutable SHA-256)
            </h4>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-3 font-mono text-[10px]">
              {activeReport.evidence.map((ev, idx) => (
                <div key={idx} className="p-3 bg-[#080f11] rounded-xl border border-outline-variant/15 flex items-center gap-2">
                  <Cpu className="h-4 w-4 text-primary shrink-0" />
                  <span className="text-on-surface-variant">{ev}</span>
                </div>
              ))}
            </div>
          </div>

          {/* Playbook Mitigation Plan */}
          <div className="space-y-3 border-t border-outline-variant/10 pt-5">
            <h4 className="text-xs font-bold font-mono text-on-surface uppercase tracking-wide">
              Mandated Playbook Mitigation Action Plan
            </h4>
            <div className="space-y-2">
              {activeReport.mitigationPlan.map((step, idx) => (
                <div key={idx} className="flex items-start gap-3 text-xs text-on-surface-variant bg-[#080f11]/40 p-2.5 rounded-lg border border-outline-variant/10">
                  <span className="w-5 h-5 rounded bg-emerald-500/10 text-emerald-400 font-mono flex items-center justify-center font-bold text-[10px] shrink-0 mt-0.5">
                    {idx + 1}
                  </span>
                  <span className="leading-relaxed">{step}</span>
                </div>
              ))}
            </div>
          </div>

        </div>

      </div>
    </div>

    {/* Cryptographic Share Panel */}
    <ShareDialog 
      isOpen={isShareOpen}
      onClose={() => setIsShareOpen(false)}
      reportId={activeReport.id}
      reportTitle={activeReport.summary}
    />

    {/* Unified Cyber Toast Notifier */}
    {toast && (
      <NotificationToast 
        message={toast.message}
        type={toast.type}
        onClose={() => setToast(null)}
      />
    )}
    </>
  );
}
